apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - name: gitlab-ilba-cat
      url: git@gitlab.ilba.cat:gitops/argocd.git
      type: git
      insecure: true 
      insecureIgnoreHostKey: true
      sshPrivateKeySecret:
        name: argo-secret
        key: ssh-Privatekey
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@gitlab.ilba.cat:gitops/argocd.git
