k8sServiceHost: "172.26.0.111"
k8sServicePort: "6443"
kubeProxyReplacement: "true"
bpf:
  masquerade: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.1.0.0/16"]
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
l2announcements:
  enabled: true
cluster:
  name: k8s-raspberry-pi-01
  id: 1
