apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-ilba-repo
  namespace: kargo-ilba-ns
  labels:
    kargo.akuity.io/cred-type: git
    kargo.akuity.io/project: kargo-ilba-ns
stringData:
  repoURL: https://github.com/oscarmash/test-argocd.git
  username: oscarmash
  password: TOKEN