apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - name: gitlab-ilba-cat
      url: git@gitlab.ilba.cat:gitops/argocd.git
      type: git
      insecure: true 
      insecureIgnoreHostKey: true
      sshPrivateKeySecret:
        name: argo-secret
        key: ssh-Privatekey
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@gitlab.ilba.cat:gitops/argocd.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEAnPBNuPWfRis+t8XKM0N7IgPv0l58Nk64WzIoCYhEodj2AwtgoqlB
    WkjNOwTPWxsA27aJgM4pSkooInzZs1dY5SoEXvdeuZ4InZjifqxGu1sE11d4JdAGAK8enZ
    sZBtik3JEhYcxIj3Ykr5W/9FLMF4jfzlsj7I63BWQXsJ6SCoa72GLADf7tryYxtce+DnOI
    3ZiHe42TAHYSJs9HhNVDKTojlB2TACfFtQSv+E/z1Nac7pQ0YtqpbVl9tZEJ0JE9X3uwUs
    V0FMeBGvNB+TLM4bgiZ/CGz0lBZ4qt4WDcDc+nc6aECe6PZDAfAniPlgUQqATNbxpFmQdv
    iGlaswGy5QU3lT0hM4bVZ3VTCNIGwmvQMc1jBuvj8VkIxVBZQ8bkpK7Pt3GrxuNT7KkDKb
    oOin+KOaiDT25UmhDpLiS6WkA2+AIQgkhaSv2h+7MzqUZsCxpaiTbTJy/R39fpjTcplY8h
    fE1Dpiyj6ssg75BRaN0ksfyh1q9RLJR4UilvxystAAAFkAopzkUKKc5FAAAAB3NzaC1yc2
    EAAAGBAJzwTbj1n0YrPrfFyjNDeyID79JefDZOuFsyKAmIRKHY9gMLYKKpQVpIzTsEz1sb
    ANu2iYDOKUpKKCJ82bNXWOUqBF73XrmeCJ2Y4n6sRrtbBNdXeCXQBgCvHp2bGQbYpNyRIW
    HMSI92JK+Vv/RSzBeI385bI+yOtwVkF7CekgqGu9hiwA3+7a8mMbXHvg5ziN2Yh3uNkwB2
    EibPR4TVQyk6I5QdkwAnxbUEr/hP89TWnO6UNGLaqW1ZfbWRCdCRPV97sFLFdBTHgRrzQf
    kyzOG4Imfwhs9JQWeKreFg3A3Pp3OmhAnuj2QwHwJ4j5YFEKgEzW8aRZkHb4hpWrMBsuUF
    N5U9ITOG1Wd1UwjSBsJr0DHNYwbr4/FZCMVQWUPG5KSuz7dxq8bjU+ypAym6Dop/ijmog0
    9uVJoQ6S4kulpANvgCEIJIWkr9ofuzM6lGbAsaWok20ycv0d/X6Y03KZWPIXxNQ6Yso+rL
    IO+QUWjdJLH8odavUSyUeFIpb8crLQAAAAMBAAEAAAGARY2GlKNe7GU8DYw+GcwdZSzje5
    Neb18h+2DWN6tJ54TVOvIu6Mgka5P6SN7P2yuzjKxwckJsMD1/XhGBFidvAVlGyKPPOmpc
    nSPltYg6bMxg7+MXH4L7NhBmfCkBxXP8VLiJV+OGgPY2Og8fHHQZeZCyx6zC1hNF78C1cx
    RD2yBtXfAd99X0lvxRaaPVimgPz03LNam/7aNmVgblRmyRsFLQ89LLlHUL/TbPmjgs8zYO
    JPpP4UPRdOIFgZN/Cw1iuSDU2N5o/1TQASDbe7JpbVRFFhL84GIUY/ZtTGn1C+U0JN+UjX
    md8DePFuWIq1E5V8UztmBlp8pfxUkS7QMQYBwoxso5dpYoTqscvJnmJ047tlCh3yhI/XNq
    BQFp9aFHKT6GQ5SmfS03YE0nn3XTYXQuA1wJAWJhT203qFKvqEKRWQlawjqlBKfo+lIMRx
    dLSMkGUfzpxYLr+e3pKzYs7e2eG5JYEgYlYORHIEHIC1CGJJlb7vXi4jLw9zk3kvUNAAAA
    wFvneL5x2zQI1tqatK29qpttRIWYPechOoEw9jRpFAHtUTOlDMVh4kVDBhegEoAy4brAyX
    TH1GePoR2F0NB9XwgqQTr//c4kEr3VwJUwrizWmHDxe4kftZI0duK1zwBi6GNk5aJ747+F
    Os0YDXw9PZ/JtSLx4syoBh0wTdnFXAhFvoBCqS6HghyQj5TaQid6tIaZMgnHLKiq2aMKvj
    5pWi+94VHidEeWjaSsgwYjKU+P41oUWtGzMcZZu2mPHLIAlgAAAMEAyxqtaEnPt43EeGPv
    jYiaZreKY/MQ23tTdTCRUOJKyo3oHjhlDSAw6dgalhms98v45F1J9llzIC5WaBeaW5d7co
    La2BG6sr3JjEVLIYDcSIUGz5F4a7q1HvK7MODuQoR8g5jOJcnDrFnh6uJZCVDD01uERNhG
    C2PiAj5jotAdYtDVeFzoGq0cVZkmWaHJS2joG9FbAvraBEb3Ksx/338yza8y60uo8JSuRA
    ESSVqJ7XQx2omwFsEMBfwny+83Hmm/AAAAwQDFz7AYIwKzo4b59/bQDmJBD/Yr6pu1N5w5
    R3WEDAJNasRZICiDzqpC6KRbRCOK6aWx2G9w/vpBoy/1D+IUkf/JMriExPH+YMmahCo1uF
    E4ZuWMU4S4IrfNGVF2ix7Tbw0RcazUxAf+cNUADXnmeThRfCZBKLpOFdQ+etuW9jvmQTnS
    Zs0dKRvIzbcmwJz1EBhXtan1dHayEVvXUqefJWw1Is1+tqLpb2K26bd1FQhsD1elK4eDSu
    occ6NvcR27LhMAAAAUb3NjYXIubWFzQGlsaW1pdC5uZXQBAgMEBQYH
    -----END OPENSSH PRIVATE KEY-----