apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-homer
  namespace: argocd
spec:
  project: ilba
  source:
    repoURL: git@gitlab.ilba.cat:gitops/argocd.git
    targetRevision: HEAD
    path: namespace/ilba-homer
  destination:
    server: https://kubernetes.default.svc
    namespace: ilba-homer
  syncPolicy:
    automated: {}
---
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sync-app-homer
spec:
  syncWindows:
  - kind: allow
    schedule: '* * * * *'
    duration: 15m
    applications:
    - 'app-homer'
    manualSync: true