global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'federation'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="node-exporter"}'
    static_configs:
      - targets:
        - '172.26.0.202:9090'
        - '172.26.0.203:9090'
