apiVersion: v1
kind: Namespace
metadata:
  name: test-egress-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-egress-gateway-deployment
  namespace: test-egress-gateway
  labels:
    app.kubernetes.io/name: app-ilba
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-ilba
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-ilba
    spec:
      containers:
        - name: egress-gateway
          image: debian:12
          command:
            - "sleep"
            - "604800"
          imagePullPolicy: IfNotPresent
