k8sServiceHost: "auto"
k8sServicePort: "auto"
kubeProxyReplacement: "true"
bpf:
  masquerade: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.2.0.0/16"]
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
l2announcements:
  enabled: true
cluster:
  name: k8s-cilium-02
  id: 2
clustermesh:
  useAPIServer: true
  config:
    enabled: true
    clusters:
      - name: k8s-cilium-01
        port: 32379
        id: 1
        ips:
          - 172.26.0.141
      - name: k8s-cilium-02
        port: 32379
        id: 2
        ips:
          - 172.26.0.145
  apiserver:
    tls:
      authMode: cluster
      auto:
        enabled: true
        method: cronJob
        schedule: "0 0 1 */4 *"