- name: Custom pre install - SWAP
  hosts: k8s_cluster
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    bashrc: /root/.bashrc
  tasks:

    - name: Disable SWAP since kubernetes can't work with swap enabled
      shell: |
        swapoff -a

    - name: Remove multiple packages
      apt:
        name:
          - dphys-swapfile
          - zram-tools
        state: absent

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'