apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: oscarmash@gmail.com
    privateKeySecretRef:
      name: clusterissuer-key
    solvers:
    - http01:
       ingress:
         class: nginx