apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-nvme
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.3
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    ssl: false
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "2025-07"
        devices:
          - name: "nvme0n1p3"
      - name: "2025-09"
        devices:
          - name: "nvme0n1p3"
      - name: "2025-11"
        devices:
          - name: "nvme0n1p3"
