---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-conf-pvc
  namespace: ilba-plex
  labels:
    app: plexserver
spec:
  storageClassName: nfs-plex-conf
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-conf-pv
  namespace: ilimit-plex
  labels:
    app: plexserver
spec:
  storageClassName: nfs-plex-conf
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.26.0.58
    path: "/nfs-k8s/k8s_plex/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-pvc
  namespace: ilba-plex
  labels:
    app: plexserver
spec:
  storageClassName: nfs-plex-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data-pv
  namespace: ilimit-plex
  labels:
    app: plexserver
spec:
  storageClassName: nfs-plex-data
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.26.0.58
    path: "/nfs-k8s/k8s_plex/data"