apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: ilba
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.15
    helm:
      releaseName: nfs-subdir-external-provisioner
      values: |
        nfs:
          server: 172.26.0.58
          path: "/nfs-k8s/k8s_dynamic"
        storageClass:
          create: true
          defaultClass: true
          name: nfs-client
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-nfs