api:
  adminAccount:
    passwordHash: '$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm'
    tokenSigningKey: oPknUGb3DEuwvSaBgrqLusL2HgoirtbR
  ingress:
    enabled: false
  service:
    type: NodePort
    nodePort: 30443
certManager:
  enabled: true
controller:
  argorollouts:
    integrationEnabled: false