apiVersion: v1
kind: Service
metadata:
  name: svc-traffic-distribution
  namespace: traffic-distribution
  annotations:
    service.kubernetes.io/topology-mode: Auto
spec:
  selector:
    app.kubernetes.io/name: app-ilba
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  trafficDistribution: PreferSameZone
