global:
  dnsService: "coredns"

chunksCache:
  allocatedMemory: 100

loki:
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-k8s
      ruler: loki-k8s
      admin: loki-k8s
    type: s3
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      accessKeyId: loki
      secretAccessKey: We2spertaudO12
      s3ForcePathStyle: true
      insecure: false
      http_config:
        insecure_skip_verify: true
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-09-28
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  compactor:
    working_directory: /data/retention
    compaction_interval: 5m
    retention_enabled: true
    retention_delete_delay: 10m
    retention_delete_worker_count: 150
    delete_request_store: s3
  limits_config:
    retention_period: 15m

write:
  replicas: 1
  persistence:
    volumeClaimsEnabled: false

read:
  replicas: 1
  persistence:
    volumeClaimsEnabled: false

gateway:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: loki-gateway.ilba.cat
        paths:
          - path: /
            pathType: Prefix
    tls: []

  basicAuth:
    enabled: true
    username: loki-gateway
    password: loki-gateway-password

backend:
  replicas: 1
  extraVolumeMounts:
  - name: compactor-data
    mountPath: /data/retention
  extraVolumes:
    - name: compactor-data
      emptyDir: {}

test:
  enabled: false

lokiCanary:
  enabled: false
